[general]
import = [
    "/home/rash/.config/alacritty/themes/tokyonight_deep.toml",
]

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "GeistMono NFM"
style = "Regular"

[font.bold]
family = "GeistMono NFM"
style = "Bold"

[font.italic]
family = "GeistMono NFM"
style = "Italic"

[font.bold_italic]
family = "GeistMono NFM"
style = "Bold Italic"

[font.offset]
x = 0
y = 0

[cursor.style]
shape = "Block"
blinking = "On"

[mouse]
hide_when_typing = true
bindings = []

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/bin/zsh"

[window]
opacity = 0.4
dynamic_padding = true

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 20

[keyboard]
bindings = [
    { key = "p", mods = "Shift|Control", action = "ToggleViMode" },
    { key = "Home", mods = "None", chars = "\u001bOH" },
    { key = "End", mods = "None", chars = "\u001bOF" },
    { key = "Left", mods = "Alt", chars = "\u001b[1;3D" },
    { key = "Right", mods = "Alt", chars = "\u001b[1;3C" },
]
