[global]
workgroup = WORKGROUP
server string = linuxmini Samba Server
security = user
map to guest = Bad User

# macOS compatibility
vfs objects = catia fruit streams_xattr
fruit:metadata = stream
fruit:resource = file
fruit:locking = none
fruit:posix_rename = yes
fruit:zero_file_id = yes
fruit:nfs_aces = no
fruit:veto_appledouble = no
fruit:wipe_intentionally_left_blank_rfork = yes

[plateshare]
path = /home/rash/.config/cjar/plates/share
browseable = no
read only = no
guest ok = no
force user = rash
valid users = rash

[rashshare]
path = /home/rash/samba_share
browseable = no
read only = no
guest ok = no
force user = rash
valid users = rash
