# SOPS configuration for secrets management
# Public key extracted from ~/.config/sops/age/keys.txt
keys:
  - &linuxmini age1q366mx62s06sdkf2l3mkz6y62wfga0ncvsl4ymlvxqjk69vcqgvsmjpmxz
  - &workmbp age14x963l7j53w6psuuvsefsj5js5xwd6wue5csgg6mjzd568vwtgasjynzq7
  - &oldmbp age12kmuh5f5v9zf9wcfplh8klwtpedrplr4xzu7ztpfznqyd3f7qqfqu54pzu
  - &thor age1jcreaq0xkudylh9klng85e56y30l23dyfxntkq6vcvwfxh06hfysq4lpcx

creation_rules:
  # Common secrets for all machines
  - path_regex: secrets/common\.yaml$
    key_groups:
      - age:
          - *linuxmini
          - *workmbp
          - *oldmbp
          - *thor

  # Linux-specific secrets (linuxmini + oldmbp + thor)
  - path_regex: secrets/linux\.yaml$
    key_groups:
      - age:
          - *linuxmini
          - *oldmbp
          - *thor

  # Linuxcommon secrets (shared between Linux machines)
  - path_regex: linuxcommon/secrets/linuxcommon\.yaml$
    key_groups:
      - age:
          - *linuxmini
          - *oldmbp
          - *thor

  # Darwin/macOS-specific secrets
  - path_regex: secrets/darwin\.yaml$
    key_groups:
      - age:
          - *linuxmini  # Can access from linuxmini for editing
          - *workmbp

  # Machine-specific: linuxmini
  - path_regex: secrets/linuxmini\.yaml$
    key_groups:
      - age:
          - *linuxmini

  # Machine-specific: workmbp
  - path_regex: secrets/workmbp\.yaml$
    key_groups:
      - age:
          - *linuxmini  # Can access from linuxmini for editing
          - *workmbp

  # Machine-specific: thor
  - path_regex: secrets/thor\.yaml$
    key_groups:
      - age:
          - *linuxmini  # Can access from linuxmini for editing
          - *thor

  # Machine-specific Claude secrets: workmbp
  - path_regex: workmbp/secrets/claude\.yaml$
    key_groups:
      - age:
          - *linuxmini  # Can access from linuxmini for editing
          - *workmbp

  # Machine-specific configs: workmbp (sqlit, etc.)
  - path_regex: workmbp/config/\.sqlit/.*\.json$
    key_groups:
      - age:
          - *linuxmini  # Can access from linuxmini for editing
          - *workmbp

  # Claude Code secrets for all machines
  - path_regex: common/secrets/claude\.yaml$
    key_groups:
      - age:
          - *linuxmini
          - *workmbp
          - *oldmbp
          - *thor
