theme = "tokyonight_deep" # theme_it: injected at 2025-04-13 22:39:58 # theme_it: injected at 2025-04-13 22:37:06 # theme_it: injected at 2025-04-13 22:30:55 # theme_it: injected at 2025-04-13 22:09:27

[editor]
bufferline = "multiple"
clipboard-provider = "wayland"
line-number = "relative"
mouse = false
rulers = [80, 120]
true-color = true
auto-completion = true
cursorline = true
end-of-line-diagnostics = "error"
color-modes = true

[editor.cursor-shape]
insert = "bar"       # Thin vertical line in insert mode
normal = "block"     # Block cursor in normal mode
select = "underline" # Underline cursor in select mode

[editor.indent-guides]
render = true
character = "┆"  # Character used for indentation guides
skip-levels = 1  # Skip rendering for the first level

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = ["file-type", "separator", "version-control"]
right = ["position", "position-percentage", "total-line-numbers"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "disable"

[editor.lsp]
display-messages = true
auto-signature-help = true

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.gutters.line-numbers]
min-width = 2

[editor.file-picker]
hidden = false
ignore = true
git-ignore = false
parents = true
follow-symlinks = true

[editor.search]
smart-case = true  # Case-insensitive search unless uppercase is used
wrap-around = true # Wrap around when searching past the end

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
"'" = "'"
'<' = '>'

[keys.normal]
"*" = ["search_selection", "search_next"]
"x" = ["extend_to_line_bounds", "select_mode"]
"A-B" = ["goto_prev_paragraph", "collapse_selection", "goto_next_paragraph"]

# Navigate
"C-j" = "@5j"
"C-k" = "@5k"

# Splitting windows
"A-V" = ":vsplit"       # Vertical split
"A-S" = ":hsplit"       # Horizontal split
"A-D" = "wclose"

# Navigating between windows
"A-H" = "jump_view_left"         # Move focus left
"A-J" = "jump_view_down"         # Move focus down
"A-K" = "jump_view_up"           # Move focus up
"A-L" = "jump_view_right"        # Move focus right

[keys.select]
"x" = [ "extend_line" ]