
theme = "catppuccin-mocha"

[editor]
bufferline = "multiple"
clipboard-provider = "wayland"
line-number = "relative"
mouse = false
rulers = [80, 120]
true-color = true
auto-completion = true
cursorline = true
end-of-line-diagnostics = "error"

[editor.cursor-shape]
insert = "bar"       # Thin vertical line in insert mode
normal = "block"     # Block cursor in normal mode
select = "underline" # Underline cursor in select mode

[editor.indent-guides]
render = true
character = "┆"  # Character used for indentation guides
skip-levels = 1  # Skip rendering for the first level

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = ["file-type", "separator", "version-control"]
right = ["position", "position-percentage", "total-line-numbers"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "disable"

[editor.lsp]
display-messages = true
auto-signature-help = true

#[[editor.whitespace.render]]
#mode = "all"  # Show spaces, tabs, and newlines
#except = ["markdown"]

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.gutters.line-numbers]
min-width = 2

[editor.file-picker]
hidden = false
ignore = true
git-ignore = false
parents = true
follow-symlinks = true

[editor.search]
smart-case = true  # Case-insensitive search unless uppercase is used
wrap-around = true # Wrap around when searching past the end

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
"'" = "'"
'<' = '>'

[keys.normal]
"*" = ["search_selection", "search_next"]
Y = ":clipboard-yank" # Yank to system clipboard
V = ":clipboard-paste-after" # Paste from system clipboard

# Splitting windows
"C-S-v" = ":vsplit"       # Vertical split
"C-S-s" = ":hsplit"       # Horizontal split

# Navigating between windows
"C-S-h" = "jump_view_left"         # Move focus left
"C-S-j" = "jump_view_down"         # Move focus down
"C-S-k" = "jump_view_up"           # Move focus up
"C-S-l" = "jump_view_right"        # Move focus right

