[[language]]
name = "python"
scope = "source.python"
file-types = ["py"]
language-servers = ["pylsp", "ruff"]
auto-format = true
formatter = { command = "sh", args = ["-c", "black --quiet - | isort -"] }

[language-server.pylsp]
command = "pylsp"

[language-server.pylsp.config.pylsp.plugins]
jedi_completion = { enabled = true }
jedi_hover = { enabled = true }
jedi_references = { enabled = true }
jedi_signature_help = { enabled = true }
jedi_symbols = { enabled = true, all_scopes = true }
ruff = { enabled = true }
black = { enabled = true }
pycodestyle = { enabled = false }
pydocstyle = { enabled = false }

[language-server.ruff]
command = "ruff"
args = ["lsp"]

