# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[mgr]
cwd = { fg = "#00ffbb" }

# Hovered
hovered         = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#ffee00", bold = true, italic = true, underline = true }
find_position = { fg = "#d5a6ff", bg = "reset", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#41a6b5", bg = "#41a6b5" }
marker_cut      = { fg = "#f7768e", bg = "#f7768e" }
marker_marked   = { fg = "#00ffbb", bg = "#00ffbb" }
marker_selected = { fg = "#ffee00", bg = "#ffee00" }

# Tab
tab_active   = { reversed = true }
tab_inactive = {}
tab_width    = 1

# Count
count_copied   = { fg = "#1d1d2c", bg = "#41a6b5" }
count_cut      = { fg = "#1d1d2c", bg = "#f7768e" }
count_selected = { fg = "#1d1d2c", bg = "#ffee00" }

# Border
border_symbol = "│"
border_style  = { fg = "#494d5e" }

# : }}}


# : Tabs {{{

[tabs]
active   = { fg = "#1d1d2c", bg = "#7aa2f7", bold = true }
inactive = { fg = "#7aa2f7", bg = "#363b54" }

# : }}}


# : Mode {{{

[mode]

normal_main = { fg = "#1d1d2c", bg = "#7aa2f7", bold = true }
normal_alt  = { fg = "#7aa2f7", bg = "#363b54" }

# Select mode
select_main = { fg = "#1d1d2c", bg = "#00ffbb", bold = true }
select_alt  = { fg = "#00ffbb", bg = "#363b54" }

# Unset mode
unset_main = { fg = "#1d1d2c", bg = "#ff5f8f", bold = true }
unset_alt  = { fg = "#ff5f8f", bg = "#363b54" }

# : }}}


# : Status bar {{{

[status]
# Permissions
perm_sep   = { fg = "#494d5e" }
perm_type  = { fg = "#7aa2f7" }
perm_read  = { fg = "#ffee00" }
perm_write = { fg = "#f7768e" }
perm_exec  = { fg = "#41a6b5" }

# Progress
progress_label  = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#7aa2f7", bg = "#454c6d" }
progress_error  = { fg = "#f7768e", bg = "#454c6d" }

# : }}}


# : Pick {{{

[pick]
border   = { fg = "#7aa2f7" }
active   = { fg = "#d5a6ff", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "#7aa2f7" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[cmp]
border = { fg = "#7aa2f7" }

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#7aa2f7" }
title   = {}
hovered = { fg = "#d5a6ff", underline = true }

# : }}}


# : Which {{{

[which]
mask            = { bg = "#363b54" }
cand            = { fg = "#00ffbb" }
rest            = { fg = "#b9bdcc" }
desc            = { fg = "#d5a6ff" }
separator       = "  "
separator_style = { fg = "#494d5e" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#00ffbb" }
run     = { fg = "#d5a6ff" }
hovered = { reversed = true, bold = true }
footer  = { fg = "#363b54", bg = "#d0d6e3" }

# : }}}


# : Notify {{{

[notify]
title_info  = { fg = "#41a6b5" }
title_warn  = { fg = "#ffee00" }
title_error = { fg = "#f7768e" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
        # Images
        { mime = "image/*", fg = "#00ffbb" },

        # Media
        { mime = "{audio,video}/*", fg = "#ffee00" },

        # Archives
        { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#d5a6ff" },

        # Documents
        { mime = "application/{pdf,doc,rtf}", fg = "#41a6b5" },

        # Fallback
        { name = "*", fg = "#d0d6e3" },
        { name = "*/", fg = "#7aa2f7" }
]

# : }}}