

[palette]
fg = "#ffffff"
bg = "#010111"
cursor = "#7dcfff"
selection_foreground = "#ffffff"
selection_background = "#515c7e"
red = "#ff5f8f"
orange = "#ffee00"
yellow = "#ffee00"
light-green = "#00ffbb"
green = "#41a6b5"
aqua = "#7dcfff"
teal = "#7dcfff"
turquoise = "#8bffff"
light-cyan = "#8bffff"
cyan = "#8bffff"
blue = "#82aaff"
purple = "#bb9af7"
magenta = "#d5a6ff"
comment = "#4a3e6b"
black = "#363b54"
add = "#00ffbb"
change = "#82aaff"
delete = "#ff5f8f"
error = "#ff5f8f"
info = "#8bffff"
hint = "#7dcfff"
fg-dark = "#b9bdcc"
fg-gutter = "#25263d"
fg-linenr = "#d0d6e3"
fg-selected = "#0b0c19"
border = "#363b54"
border-highlight = "#8bffff"
bg-inlay = "#0d2136"
bg-selection = "#515c7e"
bg-menu = "#0b0c19"
bg-focus = "#494d5e"
