#!/usr/bin/env bash

PROFILE=$1
QUTE_BASE="$HOME/.config/qutebrowser/profiles/$PROFILE"

if [ ! -d "$QUTE_BASE" ]; then
    echo "❌ Profile '$PROFILE' doesn't exist."
    exit 1
fi

qutebrowser --basedir "$QUTE_BASE" &
disown
