
attribute = { fg = "color14" }
comment = { fg = "color8", modifiers = ["italic"] }
"comment.block.documentation" = { fg = "color11" }
constant = { fg = "color9" }
"constant.builtin" = { fg = "color14" }
"constant.character" = { fg = "color10" }
"constant.character.escape" = { fg = "color13" }
constructor = { fg = "color14" }
function = { fg = "color4", modifiers = ["italic"] }
"function.builtin" = { fg = "color14" }
"function.macro" = { fg = "color14" }
"function.special" = { fg = "color14" }
keyword = { fg = "color5", modifiers = ["italic"] }
"keyword.control" = { fg = "color13" }
"keyword.control.import" = { fg = "color14" }
"keyword.control.return" = { fg = "color5", modifiers = ["italic"] }
"keyword.directive" = { fg = "color14" }
"keyword.function" = { fg = "color13" }
"keyword.operator" = { fg = "color13" }
label = { fg = "color4" }
namespace = { fg = "color14" }
operator = { fg = "color6" }
punctuation = { fg = "color6" }
special = { fg = "color14" }
string = { fg = "color10" }
"string.regexp" = { fg = "color14" }
"string.special" = { fg = "color14" }
tag = { fg = "color13" }
type = { fg = "color14" }
"type.builtin" = { fg = "color14" }
"type.enum.variant" = { fg = "color9" }
variable = { fg = "foreground" }
"variable.builtin" = { fg = "color1" }
"variable.other.member" = { fg = "color2" }
"variable.parameter" = { fg = "color11", modifiers = ["italic"] }

"markup.bold" = { modifiers = ["bold"] }
"markup.heading" = { fg = "color4", modifiers = ["bold"] }
"markup.heading.completion" = { bg = "color24", fg = "foreground" }
"markup.heading.hover" = { bg = "color15" }
"markup.italic" = { modifiers = ["italic"] }
"markup.link" = { fg = "color4", underline = { style = "line" } }
"markup.link.label" = { fg = "color14" }
"markup.link.text" = { fg = "color14" }
"markup.link.url" = { underline = { style = "line" } }
"markup.list" = { fg = "color9", modifiers = ["bold"] }
"markup.normal.completion" = { fg = "color8" }
"markup.normal.hover" = { fg = "color7" }
"markup.raw" = { fg = "color14" }
"markup.raw.inline" = { bg = "color0", fg = "color4" }
"markup.strikethrough" = { modifiers = ["crossed_out"] }

"diff.delta" = { fg = "color4" }
"diff.delta.moved" = { fg = "color4" }
"diff.minus" = { fg = "color9" }
"diff.plus" = { fg = "color2" }

error = { fg = "color9" }
warning = { fg = "color11" }
info = { fg = "color14" }
hint = { fg = "color14" }
"diagnostic.error" = { underline = { style = "curl", color = "color9" } }
"diagnostic.warning" = { underline = { style = "curl", color = "color11" } }
"diagnostic.info" = { underline = { style = "curl", color = "color14" } }
"diagnostic.hint" = { underline = { style = "curl", color = "color14" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

"ui.background" = { bg = "background", fg = "foreground" }
"ui.cursor" = { modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "color9", modifiers = ["bold"] }
"ui.cursorline.primary" = { bg = "color24" }
"ui.help" = { bg = "color24", fg = "foreground" }
"ui.linenr" = { fg = "color16" }
"ui.linenr.selected" = { fg = "color7" }
"ui.menu" = { bg = "color24", fg = "foreground" }
"ui.menu.selected" = { bg = "color15" }
"ui.popup" = { bg = "color24", fg = "color14" }
"ui.selection" = { bg = "color23" }
"ui.selection.primary" = { bg = "color23" }
"ui.statusline" = { bg = "color24", fg = "foreground" }
"ui.statusline.inactive" = { bg = "color24", fg = "color16" }
"ui.statusline.normal" = { bg = "color24", fg = "foreground" }
"ui.statusline.insert" = { bg = "color9", fg = "background", modifiers = ["bold"] }
"ui.statusline.select" = { bg = "color13", fg = "background", modifiers = ["bold"] }
"ui.text" = { bg = "background", fg = "foreground" }
"ui.text.focus" = { bg = "color22" }
"ui.text.inactive" = { fg = "color8", modifiers = ["italic"] }
"ui.text.info" = { bg = "color24", fg = "foreground" }
"ui.text.directory" = { fg = "color14" }
"ui.virtual.ruler" = { bg = "color16" }
"ui.virtual.whitespace" = { fg = "color16" }
"ui.virtual.inlay-hint" = { bg = "color24", fg = "color14" }
"ui.virtual.jump-label" = { fg = "color9", modifiers = ["bold"] }
"ui.window" = { fg = "color0", modifiers = ["bold"] }

# __THEME__NAME__ palette injected by theme_it
__PALETTE__BLOCK__