"""
Setup SSH config and authorized_keys.
"""

import subprocess
from pathlib import Path

from symlink_utils import create_symlink


def setup_ssh(dotfiles_dir, hostname, home):
    """Setup SSH config and authorized_keys"""
    print("\n🔐 Step 5: Setting up SSH config and authorized_keys...")
    ssh_dir = home / ".ssh"
    ssh_dir.mkdir(mode=0o700, exist_ok=True)

    # Symlink SSH config from dotfiles (prefer machine-specific, fall back to common)
    machine_ssh_config = dotfiles_dir / hostname / "ssh" / "config"
    common_ssh_config = dotfiles_dir / "common" / "ssh" / "config"
    ssh_config_target = ssh_dir / "config"

    if machine_ssh_config.exists():
        ssh_config_source = machine_ssh_config
        # Ensure source file has correct permissions (600)
        subprocess.run(["chmod", "600", str(ssh_config_source)], check=True)
        create_symlink(ssh_config_source, ssh_config_target, f"SSH config ({hostname})")
    elif common_ssh_config.exists():
        ssh_config_source = common_ssh_config
        # Ensure source file has correct permissions (600)
        subprocess.run(["chmod", "600", str(ssh_config_source)], check=True)
        create_symlink(ssh_config_source, ssh_config_target, "SSH config (common)")
    else:
        print(f"⚠️  SSH config not found in {machine_ssh_config} or {common_ssh_config}")

    # Assemble authorized_keys from per-machine public key files
    keys_dir = dotfiles_dir / "common" / "ssh" / "keys"
    authorized_keys_target = ssh_dir / "authorized_keys"

    pub_files = sorted(keys_dir.glob("*.pub")) if keys_dir.exists() else []
    if pub_files:
        lines = ["# Auto-generated by dotfiles setup.py - do not edit manually"]
        for pub_file in pub_files:
            lines.append(f"\n# {pub_file.stem}")
            lines.append(pub_file.read_text().strip())
        authorized_keys_target.write_text("\n".join(lines) + "\n")
        authorized_keys_target.chmod(0o600)
        print(f"✅ Generated authorized_keys from {len(pub_files)} key(s) in common/ssh/keys/")
    else:
        print(f"⚠️  No .pub files found in {keys_dir}")
