
[colors.primary]
background = "@background"
foreground = "@foreground"
dim_foreground = "@color23"
bright_foreground = "@color15"

[colors.cursor]
text = "@background"
cursor = "@cursor"

[colors.vi_mode_cursor]
text = "@background"
cursor = "@color12"

[colors.search.matches]
foreground = "@background"
background = "@color30"

[colors.search.focused_match]
foreground = "@background"
background = "@accent"

[colors.footer_bar]
foreground = "@color15"
background = "@color24"

[colors.hints.start]
foreground = "@background"
background = "@accent"

[colors.hints.end]
foreground = "@color15"
background = "@color24"

[colors.selection]
text = "@foreground"
background = "@color21"

[colors.normal]
black   = "@color0"
red     = "@color1"
green   = "@color2"
yellow  = "@color3"
blue    = "@color4"
magenta = "@color5"
cyan    = "@color6"
white   = "@color7"

[colors.bright]
black   = "@color8"
red     = "@color9"
green   = "@color10"
yellow  = "@color11"
blue    = "@color12"
magenta = "@color13"
cyan    = "@color14"
white   = "@color15"

#[colors.indexed]
#16 = "@color16"
#17 = "@color17"
#18 = "@color18"
#19 = "@color19"
#20 = "@color20"
#21 = "@color21"
#22 = "@color22"
#23 = "@color23"

[colors.dim]
black   = "@color24"
red     = "@color25"
green   = "@color26"
yellow  = "@color27"
blue    = "@color28"
magenta = "@color29"
cyan    = "@color30"
white   = "@color31"
